body:
  - type: dropdown
    attributes:
      name: default_browser
      label: Default Browser
      defaultValue: Chrome
      options:
        - Chrome
        - Firefox
        - Firefox Nightly
        - Edge
        - Brave
        - Brave Nightly
        - Opera
        - Vivaldi
        - Arc
        - Zen
        - Floorp
        - Thorium
        - Custom (Chromium)
        - Custom (Firefox)
  - type: inputWithFolderBtn
    attributes:
      name: custom_profile_path
      label: Custom Profile Folder