body:
  - type: dropdown
    attributes:
      name: default_browser
      label: Choose a Browser or Profile
      defaultValue: Chrome
      options:
        - Chrome
        - Firefox
        - Firefox Nightly
        - Edge
        - Brave
        - Brave Nightly
        - Opera
        - Vivaldi
        - Arc
        - Zen
        - Floorp
        - Thorium
        - Helium
        - Waterfox
        - Chromium Profile
        - Firefox Profile
  - type: checkbox
    attributes:
      name: profile_last_updated
      label: Use the Most Recently Used Profile
      defaultValue: 'false'
  - type: inputWithFolderBtn
    attributes:
      name: custom_profile_path
      label: Browser Profile Folder Path
      defaultValue: ''
      description: Only needed if picked "Chromium Profile" or "Firefox Profile".
  - type: checkbox
    attributes:
      name: all_browsers_history
      label: Combine History from All Browsers
      defaultValue: 'false'
  - type: input
    attributes:
      name: history_limit
      label: Number of History Items to Load 
      defaultValue: '10000'
      description: This is the maximum number of history entries to load for each browser. The default is 10,000.
  - type: textarea
    attributes:
      name: blocked_domains
      label: Blocked Domains
      defaultValue: ''
      description: Comma-separated list of domains to exclude from search results (e.g., facebook.com, twitter.com).


