body:
  - type: dropdown
    attributes:
      name: default_browser
      label: Default Browser
      defaultValue: Chrome
      options:
        - Chrome
        - Firefox
        - Firefox Nightly
        - Edge
        - Brave
        - Brave Nightly
        - Opera
        - Vivaldi
        - Arc
        - Zen
        - Floorp
        - Thorium
        - Waterfox
        - Custom Chromium Profile
        - Custom Firefox Profile
  - type: checkbox
    attributes:
      name: profile_last_updated
      label: Automatically Select the Most Recently Used Profile
      defaultValue: 'false'
  - type: inputWithFolderBtn
    attributes:
      name: custom_profile_path
      label: Path to Browser Profile Folder (Required for Custom Profiles)
  - type: checkbox
    attributes:
      name: all_browsers_history
      label: Combine History from All Browsers
      defaultValue: 'false'
  - type: input
    attributes:
      name: history_limit
      label: Maximum Number of History Entries to Fetch (Per Browser)
      defaultValue: '10000'